name: Portals
main: me.japherwocky.portals.Portals
author: astaspasta, japherwocky
description: Allow players to easily build portals to another world
api-version: 1.21
version: 3.2.10
depend: [ProtocolLib]
softdepend: [BetterPortals, Vault, WorldEdit, WorldGuard, BentoBox, IridiumSkyblock, SuperiorSkyblock2, Oraxen, ItemsAdder, CustomItems, ModelEngine, LightAPI]
commands:
   portals:
      description: Main command
      usage: /<command>
      aliases: [portal]
