name: Portals
version: '1.0.0'
main: me.japherwocky.portals.Portals
api-version: '1.20'
authors: [japherwocky]
description: Create custom portals to any world or dimension
website: https://github.com/japherwocky/portals
commands:
  portals:
    description: Main portals command
    usage: /portals
    aliases: [dim, dimensions]
  portals-help:
    description: List all commands
    usage: /portals help
  portals-info:
    description: Show plugin version
    usage: /portals info
  portals-reload:
    description: Reload all configurations
    usage: /portals reload
    permission: portals.command.reload
  portals-worlds:
    description: List world names for config
    usage: /portals worlds
    permission: portals.command.worlds
  portals-clear:
    description: Delete saved portals
    usage: /portals clear <all/world/portal>
    permission: portals.command.clear
  portals-portal:
    description: Show portal info
    usage: /portals portal [name]
    permission: portals.command.portal
  portals-adminhelp:
    description: List admin commands
    usage: /portals adminHelp
  portals-permissions:
    description: List commands with permissions
    usage: /portals permissions
  portals-adminpermissions:
    description: List admin commands with permissions
    usage: /portals adminPermissions
dependencies:
  - name: ProtocolLib
    required: true
  - name: Multiverse-Core
    required: false
  - name: BetterPortals
    required: false
  - name: Vault
    required: false
  - name: WorldEdit
    required: false
  - name: WorldGuard
    required: false
  - name: BentoBox
    required: false
  - name: IridiumSkyblock
    required: false
  - name: SuperiorSkyblock2
    required: false
  - name: Oraxen
    required: false
  - name: ItemsAdder
    required: false
  - name: CustomItems
    required: false
  - name: ModelEngine
    required: false
  - name: LightAPI
    required: false
