name: Portals
version: '1.0.0'
main: me.japherwocky.portals.Portals
api-version: '1.20'
authors: [japherwocky]
description: Create custom portals to any world or dimension
website: https://github.com/japherwocky/portals
dependencies:
  - name: ProtocolLib
    required: true
  - name: Multiverse-Core
    required: false
  - name: BetterPortals
    required: false
  - name: Vault
    required: false
  - name: WorldEdit
    required: false
  - name: WorldGuard
    required: false
  - name: BentoBox
    required: false
  - name: IridiumSkyblock
    required: false
  - name: SuperiorSkyblock2
    required: false
  - name: Oraxen
    required: false
  - name: ItemsAdder
    required: false
  - name: CustomItems
    required: false
  - name: ModelEngine
    required: false
  - name: LightAPI
    required: false
